"""排版层：把论文与译文输出为 Markdown / HTML 双语对照文件。"""

from __future__ import annotations

import html
import re
from pathlib import Path

from .models import Paper


def _para_split(text: str) -> list[str]:
    """把文本按段落切分（保留 LaTeX 公式块不被拆开）。"""
    if not text:
        return []
    parts = re.split(r"\n\s*\n", text.strip())
    return [p.strip() for p in parts if p.strip()]


def _md_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace("*", "\\*").replace("_", "\\_")


def paper_to_markdown(paper: Paper, translated: str | None = None) -> str:
    """生成单篇论文的双语 Markdown（原文段落 + 译文段落对照）。"""
    lines: list[str] = []
    lines.append(f"# {paper.title}")
    lines.append("")
    lines.append(
        f"- **Authors**: {paper.authors_text}  \n"
        f"- **Year**: {paper.year_text}  \n"
        f"- **Source**: {paper.source}  \n"
        f"- **URL**: {paper.url}"
    )
    if paper.pdf_url:
        lines.append(f"- **PDF**: {paper.pdf_url}")
    lines.append("")

    if translated:
        lines.append("## 双语摘要 (Bilingual Abstract)")
        lines.append("")
        src_paras = _para_split(paper.abstract)
        tgt_paras = _para_split(translated)
        for i, src in enumerate(src_paras):
            tgt = tgt_paras[i] if i < len(tgt_paras) else ""
            if tgt:
                lines.append(f"> **中文**：{_md_escape(tgt)}")
                lines.append("")
                lines.append(f"**English**：{_md_escape(src)}")
            else:
                lines.append(f"**English**：{_md_escape(src)}")
            lines.append("")
    else:
        lines.append("## Abstract")
        lines.append("")
        lines.append(paper.abstract)
        lines.append("")

    lines.append("---")
    lines.append(f"*Generated by PaperSearch v{__import__('papersearch').__version__}*")
    return "\n".join(lines)


def papers_to_markdown(papers: list[Paper], translated: dict[str, str] | None = None) -> str:
    """生成论文列表 Markdown（含每篇的双语摘要）。"""
    translated = translated or {}
    blocks = [f"# PaperSearch 检索结果\n"]
    for idx, paper in enumerate(papers, 1):
        blocks.append(paper_to_markdown(paper, translated.get(paper.title)))
        blocks.append("")
    return "\n".join(blocks)


def markdown_to_html(md: str) -> str:
    """极简 Markdown -> HTML（标题/粗体/斜体/引用/列表），够用即可。"""
    esc = html.escape(md)
    out: list[str] = []
    in_list = False
    for raw in esc.splitlines():
        line = raw.rstrip()
        if line.startswith("# "):
            out.append(f"<h1>{line[2:]}</h1>")
        elif line.startswith("## "):
            out.append(f"<h2>{line[3:]}</h2>")
        elif line.startswith("> "):
            out.append(f"<blockquote>{line[2:]}</blockquote>")
        elif line.startswith("- "):
            if not in_list:
                out.append("<ul>")
                in_list = True
            out.append(f"<li>{line[2:]}</li>")
        elif line.startswith("*Generated by"):
            out.append(f"<p class='foot'>{line}</p>")
        elif not line:
            if in_list:
                out.append("</ul>")
                in_list = False
            out.append("")
        else:
            out.append(f"<p>{line}</p>")
    if in_list:
        out.append("</ul>")
    return "\n".join(out)


def write_output(
    content: str,
    out_dir: str | Path,
    name: str = "result",
    as_html: bool = True,
) -> Path:
    """把内容写入输出目录，返回生成的文件路径。"""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    safe = re.sub(r"[^\w\-]+", "_", name)[:80]
    md_path = out_dir / f"{safe}.md"
    md_path.write_text(content, encoding="utf-8")
    if not as_html:
        return md_path
    html_path = out_dir / f"{safe}.html"
    page = (
        "<!DOCTYPE html>\n<html lang='zh'><head><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width, initial-scale=1'>"
        f"<title>{html.escape(name)} - PaperSearch</title>"
        "<style>"
        "body{font-family:-apple-system,'Segoe UI','Microsoft YaHei',sans-serif;"
        "max-width:860px;margin:0 auto;padding:32px 20px;color:#222;line-height:1.8}"
        "h1{font-size:24px}h2{font-size:19px;border-bottom:1px solid #ddd;padding-bottom:6px;margin-top:36px}"
        "blockquote{color:#555;background:#f6f8fa;border-left:4px solid #4a90d9;"
        "margin:8px 0;padding:8px 14px;border-radius:4px}"
        "a{color:#185FA5}li{margin:4px 0}.foot{color:#999;font-size:12px}"
        "</style></head><body>\n"
        + markdown_to_html(content)
        + "\n</body></html>"
    )
    html_path.write_text(page, encoding="utf-8")
    return html_path
